#!/bin/sh
# Orquestador de Infraestructura SSO - RAULVILCHEZ.ORG

ACCION=$1

# Función para encender (Fase 1)
start() {
    echo "🚀 Preparando infraestructura de Pod (IP .27) via br_pod..."
    
    podman pod create \
      --name auth \
      --network "pasta:-4,-i,br_pod,-a,192.168.17.27,-g,192.168.17.1,-M,02:42:ac:11:00:1b,--mtu,1450,--dns,192.168.17.39,--dns-forward,192.168.17.39,--no-map-gw,-d,-l,/tmp/pasta.log" \
      --userns=keep-id
    
    echo "📦 Levantando Authelia-Auth dentro del Pod..."
    /bin/sh ./authelia-auth.sh
    
    echo "🌐 Levantando Proxy-Auth dentro del Pod..."
    /bin/sh ./proxy.sh
}

stop() {
    echo "🛑 Iniciando apagado controlado..."
    
    # Detener y eliminar el Pod (esto elimina automáticamente los contenedores internos)
    echo "📦 Eliminando infraestructura del Pod (auth-infrastructure)..."
    podman pod rm -f auth-infrastructure
    
    echo "✨ Infraestructura limpia y puerto enp9s0 liberado."
}

# Lógica de decisión corregida
case "$ACCION" in
    shutdown|stop)
        stop
        ;;
    start|up)
        start
        ;;
    *)
        echo "Uso: $0 {up|start|stop|shutdown}"
        ;;
esac